### ISSUE TITLE
PRs from forked branches aren't triggering CF builds

### ISSUE THREAD

**Issue by xTVaser** [PCSX2/pcsx2-net-www#103]
There might be an answer in their discord according to this https://community.cloudflare.com/t/pages-preview-deployments-not-triggered-by-prs-from-forks/251385

Example - https://github.com/PCSX2/pcsx2-net-www/pull/102

**Comment by seapancake** [comment]
I believe this is expected behavior as the Deploy Hook only has access to the ' PCSX2/pcsx2-net-www' repo. Can we have developers fork from PCSX2 instead? I understand some people might have their own preference however I'd rather not add peoples personal repos to the deploy hook just from an administration point of view.

**Comment by seapancake** [comment]
Could be related to https://developers.cloudflare.com/pages/platform/known-issues/ in the sense that we are only triggering builds from the pcsx2-net-www repo. I'm not familiar enough with Git to really know.

> Pages currently only supports a single project per repository. Monorepos or repositories with multiple codebases/applications currently cannot deploy more than one project to Pages at a time.

**Comment by seapancake** [comment]
Cloudflare have confirmed they don't deploy from forks to prevent abuse such as a random person deploying a crypto miner, etc.

They're working on a better solution to address this in future.

**Comment by xTVaser** [comment]
Ah ok, yeah a nice solution is if we could opt-in to do so per PR.  Until then we will just make sure to make big changes with branches on the upstream repo instead of forks -- like progress reports, etc.

And it's not like we would have had any of this functionality with github pages either.

Closing for now, hopefully things improve.
