### ISSUE TITLE
Image Comparison - Before and After Label

### ISSUE THREAD

**Issue by RedDevilus** [PCSX2/pcsx2-net-www#112]
Image Comparison doesn't state what the comparison is about like the slider does:

![image](https://user-images.githubusercontent.com/24227051/165557783-d6864f22-4bb1-4eb2-9485-e1011b2329cb.png)

The option to atleast state Before and After would be nice or even the ability to change the label.

**Comment by RedDevilus** [comment]
Default behavior:
![image](https://user-images.githubusercontent.com/24227051/165559277-20741c0f-b9a7-46d0-a4f4-3fc78af84ebb.png)

**Comment by xTVaser** [comment]
Do you think the labels should still be located on the top left/right corners or some other location (middle bottom maybe?)

**Comment by RedDevilus** [comment]
Think top is fine but i'm not against middle bottom.

**Comment by xTVaser** [comment]
kk, when in doubt -- make it configurable
