### ISSUE TITLE
[Regression] Charts not working correctly

### ISSUE THREAD

**Issue by RedDevilus** [PCSX2/pcsx2-net-www#125]
![image](https://user-images.githubusercontent.com/24227051/167730864-455ab389-b989-4721-9a06-34766c0fd713.png)

Not sure why the actual site is having issues with the charts for Q4 2021 Progress Report.

Preview Site:
[9175dfc2.pcsx2-net-www.pages.dev](https://9175dfc2.pcsx2-net-www.pages.dev/)

Actual Site:
https://pcsx2.net/blog/2022/q4-2021-progress-report/

**Comment by refractionpcsx2** [comment]
Looks to be loading a cached old version of the theme.js file

**Comment by refractionpcsx2** [comment]
Fixed by #127
