### ISSUE TITLE
CloudFlare is not properly invalidating the cache on a deploy

### ISSUE THREAD

**Issue by xTVaser** [PCSX2/pcsx2-net-www#128]
We've seen this on CSS changes, and now also on JS file changes:
- https://github.com/PCSX2/pcsx2-net-www/pull/127 this "fixed" the problem by manually busting the cache (i think)

Are we doing something wrong? CF claims that it will manually invalidate the cache, but perhaps this takes time to rollout globally?

If we cannot rely on them, we can likely manually bust the cache via hugo.

**Comment by seapancake** [comment]
seapancake@pcsx2:~$ wget -SO-  https://pcsx2.net/js/theme.js?ver=1.0  
--2022-05-11 07:39:40--  https://damonps2.net/js/theme.js?ver=1.0
Resolving damonps2.net (damonps2.net)... 2606:4700:3031::ac43:91ca, 2606:4700:3032::6815:57c6, 104.21.87.198, ...
Connecting to damonps2.net (damonps2.net)|2606:4700:3031::ac43:91ca|:443... connected.
HTTP request sent, awaiting response... 
  HTTP/1.1 200 OK
  Date: Wed, 11 May 2022 07:39:40 GMT
  Content-Type: application/javascript
  Transfer-Encoding: chunked
  Connection: keep-alive
  Access-Control-Allow-Origin: *
  Cache-Control: public, max-age=14400, must-revalidate
  ETag: W/"8513b0c9f798bcf019c5cce963cf0e55"
  Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
  Report-To: {"endpoints":[{"url":"https:\\/\\/a.nel.cloudflare.com\\/report\\/v3?s=v%2BKZTCGhSynA%2FdlJSfZKGHxaBRdMEHIvFlc3zAMo4qpWdiSw3NusRZhAeM0KnN9vakKRySR36j2N2bHQ2R13YqebgAeY3Pi4zCbEIzUgNfQjzOYD3ZhyjZE7IrzFU0TppZcBDYse49UMbiY%3D"}],"group":"cf-nel","max_age":604800}
  NEL: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
  Vary: Accept-Encoding
  CF-Cache-Status: MISS
  Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
  Content-Security-Policy: default-src 'self' github.githubassets.com cdn.jsdelivr.net api.pcsx2.net unpkg.com fonts.gstatic.com cdnjs.cloudflare.com; script-src 'self' 'unsafe-eval' 'unsafe-inline' cdn.jsdelivr.net unpkg.com cdnjs.cloudflare.com; style-src 'unsafe-inline' 'self' cdn.jsdelivr.net unpkg.com cdnjs.cloudflare.com fonts.googleapis.com fonts.gstatic.com;
  Permissions-Policy: accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=(), interest-cohort=()
  Referrer-Policy: no-referrer-when-downgrade
  X-Content-Type-Options: nosniff
  X-Frame-Options: SAMEORIGIN
  Server: cloudflare
  CF-RAY: 709943184b6f8ce2-EWR
  alt-svc: h3=":443"; ma=86400, h3-29=":443"; ma=86400
Length: unspecified [application/javascript]

#127 does not prevent caching as Cloudflare can cache URLs with query strings so this is not a fix, nor does it address the problem. 

Currently the cache is 4 hours however I'm more interested in the notes in #127 that say that deployments outside of the main branch are used for deployments on the main branch.

@xTVaser Are you seeing the same issues as @RedDevilus or something different? Do you know if it was going away after the 4 hour cache expiry?

From https://developers.cloudflare.com/pages/platform/serving-pages/

> Caching and performance
> 
> Pages comes with built in caching defaults that are optimized for caching as much as possible, while providing the most up to date content. Every time you deploy an asset to Pages, the asset remains cached on the Cloudflare CDN until your next deployment. Therefore, you should avoid setting Page Rules or custom caching on your site.
> Purging the cache
> If Page Rules or other cache settings are used on your custom domain, that may lead to stale assets being served after a new build. You can resolve this by selecting Caching > Configuration > [Purge Everything](https://developers.cloudflare.com/cache/how-to/purge-cache/#purge-everything) in the dashboard to ensure the latest build gets served."
> 
> For browser caching, Pages always sends Etag headers for 200 OK responses, which the browser then returns in an If-None-Match header on subsequent requests for that asset. Pages compares the If-None-Match header from the request with the Etag it’s planning to send, and if they match, Pages instead responds with a 304 Not Modified that tells the browser it’s safe to use what is stored in local cache.
> 
> Pages currently returns 200 responses for HTTP range requests; however, the team is working on adding spec-compliant 206 partial responses.
> 
> Pages will also serve Gzip and Brotli responses whenever possible. 

We don't have any page rules still active that should impact the caching and assuming it's not a browser issue we'll likely need to raise to Cloudflare.

**Comment by xTVaser** [comment]
Yeah I agree that i don't think #127 did anything to actually solve the problem -- it just was a manual cache bust that worked in this situation.

I'm not aware of us setting anything cache-wise and as you mention, the docs suggest that CF should invalidate the cache properly upon a deploy
> Every time you deploy an asset to Pages, the asset remains cached on the Cloudflare CDN until your next deployment. 

But as we've seen a few times, this doesn't hold true.  It seems like they will remain in the cache until that TTL is hit (4 hours apparently)

**Comment by seapancake** [comment]
Have we seen this on any of recent the dependency updates we have done? Is it still an issue?

**Comment by xTVaser** [comment]
New design is bundled via webpack so that alone might bust the cache consistently if the underlying file changes.
