### ISSUE TITLE
Pcsx2 main page is disingenuous 

### ISSUE THREAD

**Issue by Triticum0** [PCSX2/pcsx2-net-www#147]
When looking at the main page of Pcsx2 the statement made is entirely wrong

> An Open-Source Playstation 2 Emulator Supporting Over 98% Of The Original PS2 Library

This state is incorrect as over 2 thousand games haven't been so I don't know how this statement is true. If it was tested games are fair enough but the statement has no disclaimer.

**Comment by refractionpcsx2** [comment]
On top of that, our compatibility list contains 2,694 titles (of course repeats from different regions also) so there is a very generous sample size.
