### ISSUE TITLE
migrate the rest of the legacy articles

### ISSUE THREAD

**Issue by xTVaser** [PCSX2/pcsx2-net-www#15]
i did all of the 2021 progress reports, we'll want to slowly migrate legacy articles that we want.  They are created with aliases so old links will not become dead.

**Comment by seapancake** [comment]
@xTVaser How many more articles are pending to be done?

**Comment by xTVaser** [comment]
I actually resumed this work a few days ago, I'm almost done all "other articles" which just leaves progress reports (takes a while to format these) and the ones in the devblog folder.

Let me know if I should push my work up somewhere so duplicate migration work isn't done -- otherwise ill just keep plugging away at it
