### ISSUE TITLE
connecting pcsx2 to ppsspp (psp emulator) via usb

### ISSUE THREAD

**Issue by mitch03** [PCSX2/pcsx2-net-www#166]
hello, I'm hoping this can be added into an upcoming release of pcsx2, it would be nice to be able to connect pcsx2 with a usb to a psp emulator (ppsspp) to unlock some features, for example in Jak X, if you link them with a usb you unlock extra features, thanks!

**Comment by seapancake** [comment]
This repository is for website pcsx2.net issues and is not related to the emulator.
