### ISSUE TITLE
Date's text color blends with background on https://pcsx2.net/blog/

### ISSUE THREAD

**Issue by soredake** [PCSX2/pcsx2-net-www#172]
![изображение](https://user-images.githubusercontent.com/5204968/201924748-09549786-a462-4385-92eb-1d95849e7d7d.png)
![изображение](https://user-images.githubusercontent.com/5204968/201924900-235fe8d6-ff02-4244-ae13-d6b767c743ee.png)

**Comment by xTVaser** [comment]
The muted date text has been removed in the latest design
