### ISSUE TITLE
Dark Cloud crashes with internal resolution higher than 3x (Vulkan).

### ISSUE THREAD

**Issue by KainXVIII** [PCSX2/pcsx2-net-www#175]
When i open menu (with triangle button) game (and pcsx2 too) crashes, this happens when i set internal resolution to 4x or higher with Vulkan api. Game works fine with 3x IR or lower or other APIs, dx11 works fine even with 6x (but menu opens super slowly). 
PS - my config: i5-3570, 8gb ram, gtx970, win10 64bit.
PPS - this menu, i don't know what its so resource intensive lol
![DC](https://user-images.githubusercontent.com/16922126/203552503-2584b82e-d806-46c4-918a-be8fc75b2bde.jpg)

**Comment by refractionpcsx2** [comment]
Please join our discord and ask there, this repo is for website issues, not PCSX2.
