### ISSUE TITLE
RSS feed <link> does not contain full URL

### ISSUE THREAD

**Issue by LinAGKar** [PCSX2/pcsx2-net-www#182]
The `<link>` elements in the RSS feed at https://pcsx2.net/index.xml are missing the protocol and host part, `https://pcsx2.net`, instead they just start with `/`, which does not work properly. The RSS spec requires `<link>` elements to start with an [IANA-registered](http://www.iana.org/assignments/uri-schemes) URI scheme. From what I can tell, this is probably because [baseURL](https://github.com/PCSX2/pcsx2-net-www/blob/656f75b827f201d4477a1a100e30ed31c91030f0/config.yaml#L4) is set incorrectly. It's just "/", but it should be "https://pcsx2.net/".

**Comment by xTVaser** [comment]
With the switch to https://docusaurus.io/docs/blog#feed the feeds should hopefully be valid RSS/Atom/JSON

https://github.com/PCSX2/pcsx2-net-www/blob/53312870a8eca842f67d2a7b4709dd1909357bc2/docusaurus.config.js#L97-L100

Reopen if I'm mistaken!
