### ISSUE TITLE
Automatic warning for typo and spelling

### ISSUE THREAD

**Issue by RedDevilus** [PCSX2/pcsx2-net-www#198]
As the title suggests. It would diminish problems such as the lint checker for GameDB, but then applied for the site. I think LanguageTool could be potentialy used:

![image](https://user-images.githubusercontent.com/24227051/218149393-c9164c5f-d2f0-43d0-ab8e-eeaf83960dac.png)

**Comment by xTVaser** [comment]
I would say adding a CI step to check the files would be appropriate like https://github.com/marketplace/actions/github-spellcheck-action however the annoying part is whitelisting all of the jargon terms that aren't actually typos.  If someone wants to add it they definitely can.

There are also local tools like LanguageTool, or cSpell in VSCode.
