### ISSUE TITLE
Monthly tag site integration

### ISSUE THREAD

**Issue by RedDevilus** [PCSX2/pcsx2-net-www#200]
Right now it's set to launch it for every new update, which happens for most usecases, a few times per day.
Hopefully correct location to request it.

So make it so the auto-updater can target multiple cycles choices or atleast monthly for now:

Example on duckstation:
https://github.com/stenzek/duckstation/releases/tag/latest
![image](https://user-images.githubusercontent.com/24227051/218524906-fbcf8ca8-1cf1-43a9-9623-2550f2c754a6.png)

Compared to PCSX2:
![image](https://user-images.githubusercontent.com/24227051/218524977-f8d56bd1-12f9-4af8-880c-5ad750078911.png)

**Comment by xTVaser** [comment]
Probably not the right place, this would be a change in the auto-updater itself.

- Releases have associated timestamps
- The auto-updater can keep track of when it last checked
- If it's past that timeframe (ie. it's been a month) check again
- If there's a new release, notify the user, else -- check every launch until a new release is available
- reset the tracked timestamp and repeat the process.

**Comment by xTVaser** [comment]
I assume none of this is relevant anymore as stables have been released / the dev cycle has continued on.
