### ISSUE TITLE
Cloudflare blocks RSS reader from accessing RSS/Atom feeds

### ISSUE THREAD

**Issue by LinAGKar** [PCSX2/pcsx2-net-www#233]
The site seems to be using Cloudflare, with some kind of anti-scraping which blocks curl. However, this is also applied to the RSS/Atom feeds, which may cause RSS readers to be blocked.

**Comment by seapancake** [comment]
Curl isn't blocked however it's going to depend on exactly what you're doing. Can you provide some details on the setup you have and date/times and we can compare against the logs.

**Comment by LinAGKar** [comment]
I'm using Nextcloud News (user agent NextCloud-News/1.0). It tried to fetch it e.g. at 2023-06-13T10:33:10+00:00. Not sure what client exactly it uses. It might not be only curl that's blocked, though it's certainly included, because I get a 403 if I try to fetch anything from pcsx2.net with curl with its default user agent.

If I use curl with user agent "NextCloud-News/1.0", I'm able to fetch http://pcsx2.net/blog/atom.xml from any computer. However [http**s**://pcsx2.net/blog/atom.xml](https://pcsx2.net/blog/atom.xml) only works from some computers. The ones where it's working have `curl 8.1.2 (x86_64-suse-linux-gnu) libcurl/8.1.2 OpenSSL/3.1.1 zlib/1.2.13 brotli/1.0.9 zstd/1.5.5 libidn2/2.3.4 libpsl/0.21.2 (+libidn2/2.3.4) libssh/0.10.5/openssl/zlib nghttp2/1.53.0`, while the ones where it doesn't work have `curl 8.0.1 (x86_64-suse-linux-gnu) libcurl/8.0.1 OpenSSL/1.1.1l-fips zlib/1.2.11 brotli/1.0.7 zstd/1.5.0 libidn2/2.2.0 libpsl/0.20.1 (+libidn2/2.2.0) libssh/0.9.6/openssl/zlib nghttp2/1.40.0` and `curl 7.74.0 (x86_64-pc-linux-gnu) libcurl/7.74.0 OpenSSL/1.1.1n zlib/1.2.11 brotli/1.0.9 libidn2/2.3.0 libpsl/0.21.0 (+libidn2/2.3.0) libssh2/1.9.0 nghttp2/1.43.0 librtmp/2.3`. Maybe Cloudflare has something against OpenSSL 1.1.1 (Nextcloud is on the last machine, which has OpenSSL/1.1.1n).

**Comment by seapancake** [comment]
I have had a look for the user-agent and I can see it's getting blocked by the bot protection settings. Unfortunately on our plan we don't have granular control within that function to white-list certain user-agents within that function. 

I have written a new rule in our WAF which should achieve the same result, it will bypass the bot protection for the user-agent 'Nextcloud-News*' for the URL https://pcsx2.net/blog/atom.xml.

If you're still having issues if you'd be comfortable giving me your IP address on Discord we can investigate further.

**Comment by LinAGKar** [comment]
It seems to be working for me now. A user agent filter doesn't feel right tough, it could still affect other feedreaders. It doesn't feel like bot protection makes much sense at all for https://pcsx2.net/blog/atom.xml or https://pcsx2.net/blog/rss.xml, since those are meant to be ingested by bots.

**Comment by seapancake** [comment]
Good point, thats overly restrictive for the user-agent. It was skipped overall for those URLs however still required the user-agent match.

Both of the above URLs now skip all Super Bot Fight mode rules regardless of user-agent.

**Comment by seapancake** [comment]
Used an AND in the URL matching logic not an OR, have fixed this now.

**Comment by LinAGKar** [comment]
Alright, seems to be working now (well, I still get a 403 if I try to access the pages unencrypted with curl's default user agent, but that shouldn't matter since you should be using TLS).

**Comment by seapancake** [comment]
The rule only matches HTTPS and I would consider HTTP unsupported for resource access with all non-CLI connections being automatically upgraded to HTTPS.

Good to hear it's fixed now.
