### ISSUE TITLE
Wiki CAPTCHA not working

### ISSUE THREAD

**Issue by refractionpcsx2** [PCSX2/pcsx2-net-www#329]
CAPTCHA is currently not visible, users cannot log in

**Comment by bositman** [comment]
Changed CSP from this
`default-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://www.google.com/recaptcha/ https://www.googletagmanager.com/gtag/ https://pagead2.googlesyndication.com https://googleads.g.doubleclick.net; font-src https://fonts.gstatic.com/ `

to this

`default-src 'self'; 
script-src 'self' 'unsafe-inline' https://www.google.com/recaptcha/ https://www.gstatic.com/recaptcha/ https://www.recaptcha.net; 
style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; 
font-src 'self' https://fonts.gstatic.com; 
connect-src 'self' https://pagead2.googlesyndication.com https://googleads.g.doubleclick.net https://www.googletagmanager.com/gtag/; 
frame-src 'self' https://www.recaptcha.net;`

**Comment by seapancake** [comment]
Can confirm CAPTCHA loads on account creation screen now.
