### ISSUE TITLE
Move over older binaries

### ISSUE THREAD

**Issue by seapancake** [PCSX2/pcsx2-net-www#72]
These could possibly be moved onto Next Cloud.

**Comment by xTVaser** [comment]
done, archive repo is public and the API is serving em via the website.

If we want to add more dev builds (prior to 1.5) or more old stable builds (they are kinda sparse and not complete -- most dont have a linux binary, etc).  It's just a matter of adding them to the archive repo.

![image](https://user-images.githubusercontent.com/13153231/162123076-e85339b6-6daa-45c3-89c9-54734e4fe3c9.png)
