### ISSUE TITLE
what kind of blank DVD disc? DVD[-+]R[W] [DL] {4,8,16x}?

### ISSUE THREAD

**Issue by skierpage** [PCSX2/pcsx2-net-www#80]
https://pcsx2.net/guides/basic-setup/ says "Burn the ISO to a DVD" to insert in your PS2.

But there seem to be at least 7 kinds of blank DVDs: DVD-R, DVD+R DVD-RW, DVD+RW, DVD+R DL, DVD-RW, and DVD+RW, and then the different 4X, 8X, 16X speeds. Which ones work with a PlayStation 2? Which is best? If I buy a faster DVD-R and burn at a slower speed, is that as good as using "slower" DVD media?

The Internet coughs up many conflicting answers (showing that many people have this question over the decades), [e.g.](https://forums.afterdawn.com/threads/type-of-dvd-for-burning-ps2-games.459494/#post-3050484) "Also 8X DVD-R will probably work best for you. Do not use DVD+RW or DVD-RW, they will not work on most PS2's", but then someone else [wrote](https://gbatemp.net/threads/best-dvd-r-to-use-for-ps2.555242/#post-8904157) "stick with DVD+R... taiyo yuden dvd-r or +r depending which one your ps2 plays nicer with", but Taiyo Yuden is not available.

Thanks!

**Comment by seapancake** [comment]
I see this as outside the scope of what we are obligated to advise on, how the user burns the disc (brand, speed, media type, etc) is up to them. Each person potentially has a different drive that works differently per media type.

I'm assuming that your issue is in relation to the level of detail on this page? If you're asking about for your situation specifically then this is not the right place to be asking this.

**Comment by skierpage** [comment]
> Each person potentially has a different drive that works differently per media type.

Everyone reading that section has a PS2. Are you saying there is _no_ one writable DVD format that works on all PS2 models? Then please, please say so on that page. Better documentation never hurt anyone.

If I was asking about my situation I would have mentioned my PS2 model and disk burner hardware. I'm not. That page is inadequate.

**Comment by xTVaser** [comment]
I personally do not have the answer to the questions you are asking either, and the route I would take would also be googling for the answer.  

Until someone contributes a better answer, can't really improve it.  The wording was lifted from our current support wording which has been working out (presumably decently well) for years.

On a related note, I also know that USB 1.0 drives are the most successful to be compatible, but some 2.0 drives work as well....do some 3.0 ones work?  Do some 1.0 drives _not work_?  I also have no idea.

A compounding problem is all of this depends on third-party homebrew projects that we have no affiliation with, even the BIOS dumper utility itself is effectively closed source with someone who is no longer an active contributor.

**Comment by xTVaser** [comment]
Apparently DVD-R 4x is the advised media to use.

**Comment by skierpage** [comment]
> Apparently DVD-R written at 4x is the advised media to use.

Thanks! DVD-R seems the overall consensus. Some people say DVD+R is more reliable but not all PS2s support it (and I'm not asking y'all to maintain a PS2 DVD drive compatibility list :wink:). Unfortunately you can't buy 4X DVD-R media any more.

I'm ordering Verbatim 8X AZO DVD-R disks, based on my experience I'll propose a pull request for this web page, with appropriate disclaimers and caveats.

> On a related note, I also know that USB 1.0 drives are the most successful to be compatible, but some 2.0 drives work as well....do some 3.0 ones work?

?? I'm asking about what kinds of writable DVD media a PlayStation 2's built-in drive can read. I am not asking about the DVD reader/writer drive attached to my PC. (FWIW I have the Pioneer BDR-XD05S which supports everything.)

**Comment by xTVaser** [comment]
> Unfortunately you can't buy 4X DVD-R media any more.

Written at 4x speed is what matters - you can buy an 8x disc and write at a slower speed apparently.

> ?? I'm asking about what kinds of writable DVD media a PlayStation 2's built-in drive can read. I am not asking about the DVD reader/writer drive attached to my PC. (FWIW I have the Pioneer BDR-XD05S which supports everything.)

You can follow the same instructions but use a USB drive with the BIOS dumper utility instead of burning it to a DVD.
