### ISSUE TITLE
PCSX2 - system requirements tab

### ISSUE THREAD

**Issue by RedDevilus** [PCSX2/pcsx2-net-www#84]
Similar to GitHub:

![image](https://user-images.githubusercontent.com/24227051/161586903-859c9ab9-e0f3-4800-a835-6013f6e55080.png)

**Comment by seapancake** [comment]
This would seems like something best suited for the guide, especially if we rename it (See #89 ) and move it into the menu. This way the first thing users will see is what it requires to run it, doesn't makes much sense on Downloads page or anywhere else to me.
