### ISSUE TITLE
Make it more obvious there's more than just stable releases on download page

### ISSUE THREAD

**Issue by refractionpcsx2** [PCSX2/pcsx2-net-www#88]
When you're on the download page, if you're not paying attention to the scrollbar, there's no obvious thing that there is more stuff further down, it just looks like it's stable released then that's it.

Maybe worth having some quick jump style buttons at the top maybe? just something to make it a bit more obvious.

This is what I see when I go to the download page
![image](https://user-images.githubusercontent.com/6278726/162029167-a65ac9ff-e239-4669-a17a-9118e5bf088a.png)

**Comment by RedDevilus** [comment]
Maybe to the left put a pulsating Down and Up arrow indicator for scrolling down.

**Comment by RedDevilus** [comment]
Or you could do 2 buttons that do: `Jump to Nightly Builds` and `Jump to Stable Builds`

**Comment by seapancake** [comment]
I'm honestly against this idea purely on the grounds we're accommodating for people who don't see scrollbars. Which is an incredibly basic part of web page navigation.

Are we getting users who are missing the fact that development builds are below the fold?

**Comment by refractionpcsx2** [comment]
It's not the lack of scrollbar, it's the lack of noticing the scrollbar, even I fell for it briefly.  Because the page fits so perfectly on my monitor, it looks like the page is designed so the stable builds are all that's on there.  I'm not sure if a massive arrow is the right solution, sounds a bit terrible tbh :P I was just thinking more a little jump index thing at the top, or maybe have like a little menu on the side which you can click on to jump to the appropriate section.
