### ISSUE TITLE
Scripts: Make a script that detects and deletes unused assets, as well as converts to `webp`

### ISSUE THREAD

**Issue by xTVaser** [PCSX2/pcsx2-net-www#90]
During the legacy article migration, it's easy to be lazy and just copy over lots of images in bulk.

Being lazy is good, but this can create more work after the fact when half of the images are unused or need to be converted.  Such a task can easily be scripted.

**Comment by seapancake** [comment]
This is a good idea, I was doing it the REALLY lazy way by using an online tool (Which have limits but produced very good results).
