### ISSUE TITLE
Stable releases wrong release dates + misc issues

### ISSUE THREAD

**Issue by RedDevilus** [PCSX2/pcsx2-net-www#97]
Probably fetched from the dumps site, but some of these extra stable builds have no artifacts, wrongly ordered and have the same date:

![image](https://user-images.githubusercontent.com/24227051/163285031-4eeee758-31d0-4b3a-bc22-930b2e310cff.png)

**Comment by RedDevilus** [comment]
1. 1.6.0    - 07/05/2020
2. 1.4.0    - 08/01/2016
3. 1.2.1    - 02/02/2014
4. 1.0       - 01/08/2012
5. 0.9.8    - 25/03/2012
6. 0.9.7    - 05/10/2010
7. 0.9.6    - 01/03/2007
8. 0.9.4    - 11/11/2007
9. 0.9.3    - 01/04/2007
10. 0.9.2  - 18/11/2006
11. 0.9.1  - 03/07/2006
12. 0.9     - 03/04/2006
13. 0.8.1  - 17/05/2005
14. 0.7     - 16/12/2004
15. 0.6     - 23/05/2004
16. 0.5     - 24/11/2003
17. 0.4.1  - 06/08/2003
18. 0.3     - 01/05/2003
19. 0.2     - 18/02/2003
20. 0.1     - 19/12/2002
21. 0.042 - 25/09/2002
22. 0.038 - 06/07/2002
23. 0.036 - 16/06/2002
24. 0.031 - 14/04/2002
25. 0.026 - 23/03/2002

**Comment by xTVaser** [comment]
The date is the published date on the github release, we could add some sort of way to override this but that is the reason why.

They also aren't missing artifacts, all of them were from the old pcsx2.net website and many felt incomplete.  If you happen to have missing artifacts, we can add them of course.

**Comment by RedDevilus** [comment]
0.9.6 is higher than 0.9.8 for one and yes it's possible that not every windows release has a Linux equivalent.

**Comment by xTVaser** [comment]
ah sorry you are right, i made the assumption that archive builds will always be before the current repos -- this is only true for nightlies.  I'll fix that "soon"

**Comment by xTVaser** [comment]
I've fixed this in the backend, it just needs to be deployed.  Will close when that happens.

**Comment by xTVaser** [comment]
Deployed, let me know if you see any issues -- i may have made a typo somewhere.

**Comment by RedDevilus** [comment]
Download 1.4 from 05/01/2016 to 08/01/2016
0.9.6 from 05/03/2009 to 01/03/2009

Maybe also change the descriptions to match as there are 3 versions now:
- Release of Stable version (Number)
- Stable Release of v0.9.8 Linux Dependencies
- Stable Release of (Number) 

As mentioned on Discord
